basic_settings:
  site_title: Ron Bronson
  favicon_image: /images/favicon.ico

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about'
    - title: 'Speaking'
      url: '/speaking'
    - title: 'Projects'
      url: '/interviews'
    - title: 'Writing'
      url: 'https://work.ronbronson.com/'
    - title: 'Contact'
      url: 'mailto:ron@ronbronson.com'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: Built w/ Git, Jekyll, Forestry, VSCode, Google Fonts, & Netlify. 

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/ronbronson'
  instagram_url: 'https://instagram.com/ronbronson'
  snapchat_url: 'https://ronbronson.substack.com/'
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://medium.com/@ronbronson'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: 'https://work.ronbronson.com/'
  dribbble_url: 'https://dribbble.com/ronbronson'
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/quarterback'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: 'https://open.spotify.com/user/ronbronson?si=QBhUd9-7T7OcC6SdTkxJIA'
  bandcamp_url: ''
  linkedin_url: 'https://linkedin.com/in/ronbronson'

color_settings:
  background_color: '#FCFC62'
  background_alt_color: '#EAF4F4'
  text_dark_color: '#181F1C'
  text_medium_color: '#251605'
  text_light_color: '#1E212B'
  accent_color: '#EF233C'
  border_color: '#08A4BD'
  overlay_background_color: '#F2784B'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#A31621'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Solway:wght@300;400;500;700&display=swap" rel="stylesheet">'
  title_font: '"Solway", sans-serif'
  body_font: '"Solway", sans-serif'
  regular_weight: 400
  bold_weight: 500
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 500
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 700
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""